### ISSUE TITLE
Update for sensorhub

### ISSUE THREAD

**Issue by erfanoabdi** [MotorolaMobilityLLC/hardware-moto-sensors#1]
May i ask for updates on this?
for griffin or addison 8.0.0
or payton 8.1.0

griffin tag : OPL27.76-71-2-3
addison : OPNS27.76-12-22-9
payton : OPWS28.46-21-12

thanks

**Comment by vinimed** [comment]
Ticket is too old. If you are still interested on request, please re-open the issue.

**Comment by erfanoabdi** [comment]
yeah, i'm interested and waiting for release :)
